---
title: "howStanWorks"
output: html_document
---

```{stan output.var=helloWorld.stan}

/*
Print Frequency
Printing for a print statement happens every time it is executed. The transformed
data block is executed once per chain, the transformed parameter and model blocks
once per leapfrog step, and the generated quantities block once per iteration

See p84 of https://mc-stan.org/docs/2_19/reference-manual-2_19.pdf for documentation of blocks. Lots of info there.
*/
functions {
  void helloWorld() {
    print("hello world! from a function in the functions block");
  }
}

data { 
  
}

transformed data { 
  helloWorld();
 
} 
parameters { 
   
}
transformed parameters { 
  helloWorld();
 
} 

model { 
  print("Hello from the model block");
}

generated quantities { 
  print("Hello from the generated quantities block");
  // print("generated quantities being called");
} 





```


```{r}
library(rstan)
fit <-
  sampling(helloWorld.stan, algorithm = "Fixed_param",     iter=2,warmup=2)
```




```{stan output.var=shortest_stan_program}
parameters { 
  real<lower=0,upper=10> to_be_estimated;
}

model {
  print(target());
//increment_log_prob(binomial_log(y, K, phi));

}

```

```{r}
library(rstan)

fit <- sampling(shortest_stan_program, iter=1000, chains= 1)

```


# A deconstructed Stan program

```{stan output.var=pooledBattingAverage.stan}

data { 
  int<lower=0> numberOfPlayers_N;           // items, usually N
  int<lower=0> atBatsPerPlayer_K[numberOfPlayers_N];        // initial trials, sometimes K
  int<lower=0> hitsPerPlayer_y[numberOfPlayers_N];        // initial successes, usually y
} 

transformed data { //suggested best practice, verify you are getting the data you think you are
  print("numberOfPlayers_N: ",numberOfPlayers_N);
  print("atBatsPerPlayer_K: ",atBatsPerPlayer_K);
  print("hitsPerPlayer_y: ",hitsPerPlayer_y);
} 

parameters { 
  real<lower=0, upper=1> battingAverageAllPlayers_phi;  // chance of success (pooled) 
} 

model { 
 hitsPerPlayer_y ~ binomial(atBatsPerPlayer_K, battingAverageAllPlayers_phi);  // likelihood
}




```



```{stan output.var=pooledDeconstructed.stan}

functions {
  
real logProbOfBattingAverageGivenHitsAndAtBats(int hits, int atBats, real battingAverage) {
  real returnValue = 0.0;
  returnValue += lgamma(atBats +1) ;
  returnValue -= lgamma(hits + 1);
  returnValue -= lgamma(atBats - hits + 1);
  returnValue += hits*log(battingAverage);
  returnValue += (atBats - hits) * log(1-battingAverage);
  return returnValue;
}

  //overflows badly
  real probOfBattingAverageGivenHitsAndAtBats(int hits, int atBats, real battingAverage) {
    real average;
    int waysOfGettingHits;
    real probOfBattingAverage;
    waysOfGettingHits = choose(atBats,hits);
    print("choose " , waysOfGettingHits);
    probOfBattingAverage = battingAverage^hits*(1-battingAverage)^(atBats-hits);
    print("5ProbOfBattingAverage", probOfBattingAverage);
    return waysOfGettingHits * probOfBattingAverage;
    
  }

}
data { 
  int<lower=0> N;           // items 
  int<lower=0> K[N];        // initial trials 
  int<lower=0> y[N];        // initial successes 
  
} 

transformed data { 
} 

parameters { 
  real<lower=0, upper=1> phi;  // chance of success (pooled) 
   real<lower=0, upper=1> ba; 
} 

model { 
  real foo;
 // print("the model being called");
  // y ~ binomial(K, phi);  // likelihood 
 // target += binomial_lpmf(y|K, phi); - constant
 
 // print("target initial ", exp(target());
  
for (n in 1:N)  {
   // y[n] ~ binomial(K[n], phi);
   print("target before ", target());
   print("binomial_lpmf ", binomial_lpmf(y[n]|K[n], phi));
   print("logProbOfBattingAverageGivenHitsAndAtBats", logProbOfBattingAverageGivenHitsAndAtBats(y[n],K[n],phi));
   print("exp(logProbOfBattingAverageGivenHitsAndAtBats)", exp(logProbOfBattingAverageGivenHitsAndAtBats(y[n],K[n],phi)));
   
 // target += binomial_lpmf(y[n]|K[n], phi);
   target += logProbOfBattingAverageGivenHitsAndAtBats(y[n],K[n],phi);
  //battingAverage = y[n]/K[n];

   //target += battingAverage;
  // foo = probOfBattingAverageGivenHitsAndAtBats(y[n],K[n],phi);

   print(" after ",target());
}
} 

generated quantities { 
} 




```

```{stan output.var=pooledBattingAverage}
functions {
  
}

data { 
  int<lower=0> N_numberOfPlayers;           // items, usually N
  int<lower=0> K_atBatsPerPlayer[N_numberOfPlayers];        // initial trials, sometimes K
  int<lower=0> y_hitsPerPlayer[N_numberOfPlayers];        // initial successes, usually y
} 

transformed data { //suggested best practice, verify you are getting the data you think you are
  print("N_numberOfPlayers: ",N_numberOfPlayers);
  print("K_atBatsPerPlayer: ",K_atBatsPerPlayer);
  print("y_hitsPerPlayer: ",y_hitsPerPlayer);
} 

parameters { 
  real<lower=0, upper=1> phi_battingAverageAllPlayers;  // chance of success (pooled) 
  //real<lower=0, upper=1> battingAverageOnePlayer;
} 

model { 
// y_hitsPerPlayer ~ binomial(K_atBatsPerPlayer, phi_battingAverageAllPlayers);  // likelihood

//phi_battingAverageAllPlayers ~ uniform(.3,.4);
// target += uniform_lpdf(phi_battingAverageAllPlayers|.4,.7);
 //target += uniform_lpdf(phi_battingAverageAllPlayers|1,0);
 for(i in 1:N_numberOfPlayers) {
  int atBats = K_atBatsPerPlayer[i];
  int hits = y_hitsPerPlayer[i];
  for(j in 1:atBats) {
    print("target--log ",target());
    print("target--base10 ",exp(target()));
    print("");
    print("phi_battingAverageAllPlayers ",phi_battingAverageAllPlayers);
    if (j <= hits) {
      print("hit");
      //target += bernoulli_lpmf(1|phi_battingAverageAllPlayers);
      target += log(phi_battingAverageAllPlayers);
      //target += phi_battingAverageAllPlayers;
    }
    else {
      print("out");
      //target += bernoulli_lpmf(0|phi_battingAverageAllPlayers);
      target += log(1-phi_battingAverageAllPlayers);
      //target += 1-phi_battingAverageAllPlayers;
    }
 }
}
}

generated quantities { 
} 

```

R program that reads data, runs Stan program above and prints out the results. 
```{r setup, include=TRUE, echo=FALSE}
library(rstan);
#df <- read.csv("Clemente.txt", sep="\t");

dataframe <- read.csv("EfronMorrisBB.txt", sep="\t");
dataframe <- with(dataframe, data.frame(FirstName, LastName, 
                          Hits, At.Bats, 
                          RemainingAt.Bats,
                          RemainingHits = SeasonHits - Hits));


print(dataframe);


N_numberOfPlayers <- dim(dataframe)[1]
K_atBatsPerPlayer <- dataframe$At.Bats
y_hitsPerPlayer <- dataframe$Hits


M <- 1000;


fit_pool <-
  sampling(pooledBattingAverage,data=c("N_numberOfPlayers", "K_atBatsPerPlayer", "y_hitsPerPlayer"),iter=(M/2), chains=1)

print(fit_pool, c("phi_battingAverageAllPlayers"), probs=c(0.1, 0.5, 0.9));

```