---
title: "Pooling Baseball"
output: html_document
---

## Stan model to compute batting average over all players as a group, e.g., completely pooled together. 

Altenative version is McElreath's globe tossing. 


```{stan output.var=simpleStanBatting}
data { 
  int N_at_bats;           
  int y_hit1_out0[N_at_bats];
} 

parameters { 
  real phi_probabilityOfHit;  
} 

model { 
 y_hit1_out0 ~ bernoulli(phi_probabilityOfHit);  
}

generated quantities {
  real y_predicted_hits;
  y_predicted_hits = bernoulli_rng(phi_probabilityOfHit);
}

```

```{r setup, include=TRUE, echo=FALSE}
library(rstan);

number_hits <- 10
number_outs <- 40
y_hit1_out0 <- c(rep(1,number_hits),rep(0,number_outs))
N_at_bats <- length(y_hit1_out0)

M_iterations <- 1000;

fit <-
  sampling(simpleStanBatting,data=c("y_hit1_out0", "N_at_bats"),iter=(M_iterations), chains=1)

print(fit, c("phi_probabilityOfHit"), probs=c(0.1, 0.5, 0.9));

simulated_at_bats = length(unlist(extract(fit,"y_predicted_hits"),use.names=FALSE))

simulated_hits = sum(unlist(extract(fit,"y_predicted_hits"),use.names=FALSE))

print(simulated_hits/simulated_at_bats)


```

```{stan output.var=simple1}
//Can we configure sample size, num threads etc... from inside Stan program? 

parameters { 
  real<lower=0, upper=1> phi_probabilityOfHit;  
} 

model { 
 1 ~ bernoulli(phi_probabilityOfHit);  
 0 ~ bernoulli(phi_probabilityOfHit);  
 0 ~ bernoulli(phi_probabilityOfHit);  
 0 ~ bernoulli(phi_probabilityOfHit);  
 0 ~ bernoulli(phi_probabilityOfHit);  
}
```



```{r setup, include=TRUE, echo=FALSE}
library(rstan)
library("shinystan")

fit <-
  sampling(simple1)

print(fit, c("phi_probabilityOfHit"), probs=c(0.1, 0.5, 0.9))

launch_shinystan(fit)
```

adsfasf

```{stan output.var=simple2}
functions {
  
  void print_target(real target_value) {
    print("target ",target_value);
    print("target base-10 ", exp(target_value));
  }
  
  real prob_of_hit_or_out(int hit_or_out, real candidate_prob) {
    if (hit_or_out == 1) {
      return candidate_prob;
    }
    else {
      return 1 - candidate_prob;
    }
  }
}

parameters { 
  real<lower=0, upper=1> phi_probabilityOfHit;  
} 

model { 
 int hit1_out0 = 1;
 print("start of model");
 print_target(target());
 //hit1_out0 ~ bernoulli(phi_probabilityOfHit);  
 target += log(prob_of_hit_or_out(hit1_out0,phi_probabilityOfHit));
 print("end of model")
 print_target(target());
}
```

Each binary choice, hit/out, land/sea, reduces the hypothesis space by 50% but we have increased our knowledge by a constant. 





## Prediction


